version: '3.8'
services:
  web: 
    build: .
    ports: 
      - "9009:9009"
    volumes:
      - .:/app
    depends_on:
      - db
    env_file:
      - .env
    
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./postgres-data:/var/lib/postgres/data
    ports:
      - "5432:5432"